### ISSUE TITLE
Please add a license file.

### ISSUE THREAD

**Issue by railcar88** [alfonsogarciacaro/FunScript.HTML#8]
How is FunScript.HTML licensed?

**Comment by alfonsogarciacaro** [comment]
Thanks for letting me now. I added an Apache 2 license, I hope this is fine with you, please tell me if not. In any case, most of the code here will probably be integrated in the next version of FunScript itself for user's convenience.

Cheers!

**Comment by railcar88** [comment]
That works! Thanks!
